# Generated by Django 2.1.2 on 2019-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0002_auto_20190422_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebackline',
            name='approved_reason_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chargebackline',
            name='line_status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'DISPUTED')], null=True),
        ),
    ]
