# Generated by Django 2.1.2 on 2019-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0008_directcustomer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directcustomer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='directcustomer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='distributioncenter',
            unique_together=set(),
        ),
    ]
