# Generated by Django 2.1.2 on 2019-05-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0010_auto_20190502_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directcustomer',
            name='is_big3',
        ),
        migrations.AlterField(
            model_name='contract',
            name='eligibility',
            field=models.SmallIntegerField(blank=True, choices=[(None, ''), (1, 'GPO DRIVEN (BASE)'), (2, 'SUPPLIER DRIVEN'), (3, 'SUPPLIER LOC'), (4, 'INDIVIDUAL'), (5, 'BLANKET')], null=True),
        ),
    ]
