# Generated by Django 2.1.2 on 2019-05-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0011_auto_20190502_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='accounting_number',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='awp',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_old_id',
        ),
    ]
