# Generated by Django 2.1.2 on 2019-05-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0013_auto_20190514_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeback',
            name='cbid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargebackhistory',
            name='cbid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
