# Generated by Django 2.1.2 on 2019-05-23 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0014_auto_20190516_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=300)),
                ('job_title', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('function', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DirectCustomerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.Contact')),
                ('direct_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.DirectCustomer')),
            ],
            options={
                'verbose_name': 'Direct Customer - Contact',
                'verbose_name_plural': 'Direct Customers - Contacts',
                'db_table': 'direct_customers_contacts',
                'ordering': ('direct_customer',),
            },
        ),
        migrations.CreateModel(
            name='IndirectCustomerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.Contact')),
                ('indirect_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.IndirectCustomer')),
            ],
            options={
                'verbose_name': 'Indirect Customer - Contact',
                'verbose_name_plural': 'Indirect Customers - Contacts',
                'db_table': 'indirect_customers_contacts',
                'ordering': ('indirect_customer',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('email',)},
        ),
        migrations.AlterUniqueTogether(
            name='indirectcustomercontact',
            unique_together={('indirect_customer', 'contact')},
        ),
        migrations.AlterUniqueTogether(
            name='directcustomercontact',
            unique_together={('direct_customer', 'contact')},
        ),
    ]
