# Generated by Django 2.1.2 on 2019-05-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0015_auto_20190523_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('first_name',), 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='function',
            new_name='last_name',
        ),
    ]
