# Generated by Django 2.1.2 on 2019-06-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0016_auto_20190523_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirectcustomer',
            name='company_name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='indirectcustomer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indirectcustomer',
            name='location_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
