# Generated by Django 2.1.2 on 2019-06-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0017_auto_20190606_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcustomer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractcustomer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractcustomer',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'BOTH'), (1, 'DIRECT'), (2, 'INDIRECT')], null=True),
        ),
    ]
