# Generated by Django 2.1.2 on 2019-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0018_auto_20190607_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractcustomer',
            name='type',
        ),
        migrations.AddField(
            model_name='contractcustomer',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'PENDING'), (1, 'ACTIVE'), (2, 'INACTIVE')], null=True),
        ),
    ]
