# Generated by Django 2.1.2 on 2019-06-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0019_auto_20190607_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebackline',
            name='cblnid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='cblnid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directcustomer',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Distributor'), (2, 'GPO'), (3, 'Buying and Group'), (4, 'Parent')], null=True),
        ),
    ]
