# Generated by Django 2.1.2 on 2019-07-08 23:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0020_auto_20190628_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingInProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cbid', models.IntegerField(blank=True, null=True)),
                ('customer_accno', models.CharField(blank=True, max_length=100, null=True)),
                ('post_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Accounting in Process',
                'verbose_name_plural': 'Accounting in Process',
                'db_table': 'accounting_inprocess',
                'ordering': ('-post_date', 'cbid'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='accountinginprocess',
            unique_together={('cbid',)},
        ),
    ]
