# Generated by Django 2.1.2 on 2019-07-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0021_auto_20190708_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargebacklinehistory',
            old_name='error_count',
            new_name='errors_count',
        ),
    ]
