# Generated by Django 2.1.2 on 2019-08-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0022_auto_20190714_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebackline',
            name='submitted_contract_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directcustomer',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Distributor'), (2, 'GPO'), (3, 'Buying Group'), (4, 'Parent')], null=True),
        ),
    ]
