# Generated by Django 2.1.2 on 2019-08-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0023_auto_20190802_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='submitted_contract_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
