# Generated by Django 2.1.2 on 2019-08-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0025_companysetting_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncenter',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='indirectcustomer',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
