# Generated by Django 2.1.2 on 2019-09-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0026_auto_20190819_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='accounting_integration',
            field=models.IntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Acumatica')], null=True),
        ),
    ]
