# Generated by Django 2.1.2 on 2019-09-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0027_companysetting_accounting_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysetting',
            name='accounting_integration',
        ),
    ]
