# Generated by Django 2.1.2 on 2019-09-09 19:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0028_remove_companysetting_accounting_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinginprocess',
            name='errors',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='chargebackline',
            name='user_dispute_note',
            field=models.CharField(blank=True, max_length=79, null=True),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='user_dispute_note',
            field=models.CharField(blank=True, max_length=79, null=True),
        ),
    ]
