# Generated by Django 2.1.2 on 2019-09-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0030_companysetting_generate_transaction_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysetting',
            name='generate_transaction_number',
        ),
    ]
