# Generated by Django 2.1.2 on 2019-11-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0031_remove_companysetting_generate_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeback',
            name='is_received_edi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chargebackhistory',
            name='is_received_edi',
            field=models.BooleanField(default=True),
        ),
    ]
