# Generated by Django 2.1.2 on 2019-11-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0032_auto_20191110_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebackdispute',
            name='for_imports',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
