# Generated by Django 2.1.2 on 2019-11-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0033_chargebackdispute_for_imports'),
    ]

    operations = [
        migrations.AddField(
            model_name='import844',
            name='index',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
