# Generated by Django 2.1.2 on 2019-11-15 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0034_import844_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import844',
            name='index',
        ),
    ]
