# Generated by Django 2.1.2 on 2019-11-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0035_remove_import844_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargebackdispute',
            name='for_imports',
        ),
        migrations.AddField(
            model_name='chargebackdispute',
            name='for_imports_validations',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chargebackdispute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
