# Generated by Django 2.1.2 on 2019-11-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0037_remove_chargebackdispute_for_imports_validations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargebackline',
            name='errors_count',
        ),
        migrations.RemoveField(
            model_name='chargebacklinehistory',
            name='errors_count',
        ),
    ]
