# Generated by Django 2.1.2 on 2020-01-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0038_auto_20191118_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysetting',
            options={'verbose_name': 'Company Setting', 'verbose_name_plural': 'Companies Settings'},
        ),
        migrations.AddField(
            model_name='companysetting',
            name='automate_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='quickbooks_api_integration',
            field=models.BooleanField(default=False),
        ),
    ]
