# Generated by Django 2.1.2 on 2020-01-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0040_companysetting_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysetting',
            name='testing',
        ),
    ]
