# Generated by Django 2.1.2 on 2020-01-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0041_remove_companysetting_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='company_setting',
        ),
        migrations.DeleteModel(
            name='CompanySetting',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
