# Generated by Django 2.1.2 on 2020-01-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0042_auto_20200119_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcustomer',
            name='enabled_844',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directcustomer',
            name='enabled_849',
            field=models.BooleanField(default=False),
        ),
    ]
