# Generated by Django 2.1.2 on 2020-01-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0043_auto_20200125_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebackline',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('A', 'Autocorrect'), ('O', 'Override'), ('D', 'Disputed')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('A', 'Autocorrect'), ('O', 'Override'), ('D', 'Disputed')], max_length=1, null=True),
        ),
    ]
