# Generated by Django 2.1.2 on 2020-01-31 16:55

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0044_auto_20200130_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cbid', models.IntegerField(blank=True, null=True)),
                ('error', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('cleared_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Accounting - Error',
                'verbose_name_plural': 'Accounting - Errors',
                'db_table': 'accounting_errors',
                'ordering': ('accounting_transaction', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AccountingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Sent'), (3, 'Received')], default=1)),
                ('cbid', models.IntegerField(blank=True, null=True)),
                ('cb_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cb_amount_issue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('customer_accno', models.CharField(blank=True, max_length=50, null=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('items', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('cb_cm_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cb_cm_date', models.DateField(blank=True, null=True)),
                ('cb_cm_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('integration_type', models.CharField(blank=True, max_length=1, null=True)),
                ('has_error', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Accounting - Transaction',
                'verbose_name_plural': 'Accounting - Transactions',
                'db_table': 'accounting_transactions',
                'ordering': ('-created_at', 'cbid'),
            },
        ),
        migrations.AddField(
            model_name='accountingerror',
            name='accounting_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.AccountingTransaction'),
        ),
    ]
