# Generated by Django 2.1.2 on 2020-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0045_auto_20200131_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebackline',
            name='received_with_errors',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='received_with_errors',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chargeback',
            name='substage',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'NO ERRORS'), (1, 'ERRORS'), (2, 'DUPLICATES'),
                                                                (3, 'RESUBMISSIONS'), (4, 'INVALID'),
                                                                (5, 'WAITING FOR RESPONSE')], null=True),
        ),
        migrations.AlterField(
            model_name='chargebackhistory',
            name='substage',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'NO ERRORS'), (1, 'ERRORS'), (2, 'DUPLICATES'),
                                                                (3, 'RESUBMISSIONS'), (4, 'INVALID'),
                                                                (5, 'WAITING FOR RESPONSE')], null=True),
        ),
        migrations.AlterField(
            model_name='chargebackline',
            name='user_dispute_note',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='chargebacklinehistory',
            name='user_dispute_note',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
