# Generated by Django 2.1.2 on 2020-02-11 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0046_auto_20200201_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('report_type', models.SmallIntegerField(blank=True, choices=[(1, 'Contract'), (2, 'Chargeback'), (3, 'Manual')], null=True)),
                ('data_range', models.CharField(blank=True, choices=[('TD', 'Today'), ('LM', 'Last Month'), ('WTD', 'Week to Date'), ('MTD', 'Month to Date'), ('YTD', 'Year to Date'), ('TW', 'This Week'), ('LW', 'Last Week'), ('LY', 'Last Year')], max_length=5, null=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('minute', models.SmallIntegerField(blank=True, null=True)),
                ('hour', models.SmallIntegerField(blank=True, null=True)),
                ('monthday', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.SmallIntegerField(blank=True, null=True)),
                ('weekday', models.SmallIntegerField(blank=True, null=True)),
                ('recurring', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'db_table': 'scheduled_reports',
                'ordering': ('report_type', 'name'),
            },
        ),
    ]
