# Generated by Django 2.1.2 on 2020-02-11 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0047_auto_20200211_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_processing', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
                'db_table': 'recipients',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='ScheduledReportRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('myrecipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erms.Recipient')),
            ],
            options={
                'verbose_name': 'Scheduled Report - Recipient',
                'verbose_name_plural': 'Scheduled Reports - Recipients',
                'db_table': 'scheduled_reports_recipients',
                'ordering': ('scheduled_report', 'myrecipient'),
            },
        ),
        migrations.AddField(
            model_name='scheduledreportrecipient',
            name='scheduled_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.ScheduledReport'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledreportrecipient',
            unique_together={('scheduled_report', 'myrecipient')},
        ),
    ]
