# Generated by Django 2.1.2 on 2020-03-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0048_auto_20200211_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='entity1_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='entity1_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='entity1_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='entity2_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='entity2_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='entity2_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
