# Generated by Django 2.1.2 on 2020-03-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0049_auto_20200315_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirectcustomer',
            name='bid_340',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indirectcustomer',
            name='cot',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indirectcustomer',
            name='gln_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
