# Generated by Django 2.1.2 on 2020-04-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0051_remove_import844history_import844_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcustomer',
            name='nocredit',
            field=models.BooleanField(default=False),
        ),
    ]
