# Generated by Django 2.1.2 on 2020-05-04 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0052_directcustomer_nocredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOfTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_class', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('group', models.SmallIntegerField(choices=[(1, 'GOVERNMENT'), (2, 'DISTRIBUTION'), (3, 'PROVIDERS'), (4, 'RESIDENTIAL'), (5, 'NON-RETAIL PHARMACY'), (6, 'RETAIL PHARMACY'), (7, 'OTHER PURCHASERS'), (8, 'PAYERS')])),
            ],
            options={
                'verbose_name': 'Class of Trade',
                'verbose_name_plural': 'Classes of Trades',
                'db_table': 'class_of_trade',
                'ordering': ('group', 'trade_class'),
            },
        ),
        migrations.CreateModel(
            name='ContractMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(3, 'PENDING'), (1, 'ACTIVE'), (2, 'INACTIVE')], null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.Contract')),
                ('indirect_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.IndirectCustomer')),
            ],
            options={
                'verbose_name': 'Contract - Indirect Customer',
                'verbose_name_plural': 'Contracts - Indirect Customers',
                'db_table': 'contracts_indirect_customers',
                'ordering': ('contract',),
            },
        ),
    ]
