# Generated by Django 2.1.2 on 2020-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0054_auto_20200504_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cot_eval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='member_eval',
            field=models.BooleanField(default=False),
        ),
    ]
