# Generated by Django 2.1.2 on 2020-05-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0055_auto_20200506_1000'),
        ('erms', '0055_import844_bulk_id'),
    ]

    operations = [
    ]
