# Generated by Django 2.1.2 on 2020-05-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0056_merge_20200506_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountingInProcess',
        ),
    ]
