# Generated by Django 2.1.2 on 2020-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0057_delete_accountinginprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoftrade',
            name='trade_class',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
