# Generated by Django 2.1.2 on 2020-05-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0058_auto_20200512_1356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractmember',
            unique_together={('contract', 'indirect_customer', 'created_at')},
        ),
    ]
