# Generated by Django 2.1.2 on 2020-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0059_auto_20200512_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoftrade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
