# Generated by Django 2.1.2 on 2020-05-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0060_auto_20200513_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirectcustomer',
            name='cot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.ClassOfTrade'),
        ),
    ]
