# Generated by Django 2.1.2 on 2020-05-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0062_auto_20200515_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeback',
            name='stage',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'IN PROCESS'), (1, 'IMPORTED'), (2, 'VALIDATED'), (3, 'POSTED'), (4, 'PROCESSED'), (5, 'ARCHIVED')], null=True),
        ),
        migrations.AlterField(
            model_name='chargebackhistory',
            name='stage',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'IN PROCESS'), (1, 'IMPORTED'), (2, 'VALIDATED'), (3, 'POSTED'), (4, 'PROCESSED'), (5, 'ARCHIVED')], null=True),
        ),
    ]
