# Generated by Django 2.1.2 on 2020-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0063_auto_20200520_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='import844history',
            name='bulk_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
