# Generated by Django 2.1.2 on 2020-06-11 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0065_auto_20200526_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('alias', models.CharField(max_length=100)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.Contract')),
            ],
            options={
                'verbose_name': 'Contract - Alias',
                'verbose_name_plural': 'Contracts - Aliases',
                'db_table': 'contracts_aliases',
                'ordering': ('contract',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='contractalias',
            unique_together={('contract', 'alias')},
        ),
    ]
