# Generated by Django 2.1.2 on 2020-06-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0066_auto_20200611_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeback',
            name='customer_ref',
            field=models.ForeignKey(blank=True, db_column='customer_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.DirectCustomer'),
        ),
        migrations.AddField(
            model_name='chargeback',
            name='distribution_center_ref',
            field=models.ForeignKey(blank=True, db_column='distribution_center_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.DistributionCenter'),
        ),
        migrations.AddField(
            model_name='chargeback',
            name='import_844_ref',
            field=models.ForeignKey(blank=True, db_column='import_844_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.Import844History'),
        ),
        migrations.AddField(
            model_name='chargebackdispute',
            name='chargeback_ref',
            field=models.ForeignKey(blank=True, db_column='chargeback_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.ChargeBack'),
        ),
        migrations.AddField(
            model_name='chargebackdispute',
            name='chargebackline_ref',
            field=models.ForeignKey(blank=True, db_column='chargebackline_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.ChargeBackLine'),
        ),
        migrations.AddField(
            model_name='chargebackhistory',
            name='customer_ref',
            field=models.ForeignKey(blank=True, db_column='customer_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.DirectCustomer'),
        ),
        migrations.AddField(
            model_name='chargebackhistory',
            name='distribution_center_ref',
            field=models.ForeignKey(blank=True, db_column='distribution_center_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.DistributionCenter'),
        ),
        migrations.AddField(
            model_name='chargebackhistory',
            name='import_844_ref',
            field=models.ForeignKey(blank=True, db_column='import_844_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.Import844History'),
        ),
        migrations.AddField(
            model_name='chargebackline',
            name='chargeback_ref',
            field=models.ForeignKey(blank=True, db_column='chargeback_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.ChargeBack'),
        ),
        migrations.AddField(
            model_name='chargebackline',
            name='contract_ref',
            field=models.ForeignKey(blank=True, db_column='contract_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.Contract'),
        ),
        migrations.AddField(
            model_name='chargebackline',
            name='import_844_ref',
            field=models.ForeignKey(blank=True, db_column='import_844_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.Import844History'),
        ),
        migrations.AddField(
            model_name='chargebackline',
            name='indirect_customer_ref',
            field=models.ForeignKey(blank=True, db_column='indirect_customer_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.IndirectCustomer'),
        ),
        migrations.AddField(
            model_name='chargebackline',
            name='item_ref',
            field=models.ForeignKey(blank=True, db_column='item_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.Item'),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='chargeback_ref',
            field=models.ForeignKey(blank=True, db_column='chargeback_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.ChargeBack'),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='contract_ref',
            field=models.ForeignKey(blank=True, db_column='contract_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.Contract'),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='import_844_ref',
            field=models.ForeignKey(blank=True, db_column='import_844_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.Import844History'),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='indirect_customer_ref',
            field=models.ForeignKey(blank=True, db_column='indirect_customer_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.IndirectCustomer'),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='item_ref',
            field=models.ForeignKey(blank=True, db_column='item_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.Item'),
        ),
    ]
