# Generated by Django 2.1.2 on 2020-06-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0067_auto_20200619_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcot',
            name='contract_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erms.Contract'),
        ),
        migrations.AddField(
            model_name='contractcot',
            name='cot_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erms.ClassOfTrade'),
        ),
    ]
