# Generated by Django 2.1.2 on 2020-06-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0068_auto_20200619_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargebacklinehistory',
            name='chargeback_ref',
            field=models.ForeignKey(blank=True, db_column='chargeback_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.ChargeBackHistory'),
        ),
    ]
