# Generated by Django 2.1.2 on 2020-06-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0070_auto_20200624_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Pending'), (4, 'Proposed')], null=True),
        ),
        migrations.AlterField(
            model_name='contractcustomer',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Pending'), (4, 'Proposed')], null=True),
        ),
        migrations.AlterField(
            model_name='contractline',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Pending'), (4, 'Proposed')], null=True),
        ),
        migrations.AlterField(
            model_name='contractmember',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Pending'), (4, 'Proposed')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Pending'), (4, 'Proposed')], default=1, null=True),
        ),
    ]
