# Generated by Django 2.1.2 on 2020-07-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0071_auto_20200625_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='data_range',
            field=models.CharField(blank=True, choices=[('TD', 'Today'), ('YD', 'Yesterday'), ('LM', 'Last Month'), ('WTD', 'Week to Date'), ('MTD', 'Month to Date'), ('YTD', 'Year to Date'), ('TW', 'This Week'), ('LW', 'Last Week'), ('LY', 'Last Year')], max_length=5, null=True),
        ),
    ]
