# Generated by Django 2.1.2 on 2020-07-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0073_chargebackhistory_processed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcustomer',
            name='enabled_852',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directcustomer',
            name='enabled_867',
            field=models.BooleanField(default=False),
        ),
    ]
