# Generated by Django 2.1.2 on 2020-07-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0075_auto_20200709_1513'),
        ('erms', '0072_auto_20200713_0901'),
    ]

    operations = [
    ]
