# Generated by Django 2.1.2 on 2020-08-11 13:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0076_merge_20200722_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='report_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Contract'), (2, 'Chargeback'), (3, 'Manual'), (4, 'AMP'), (5, 'CB DETAIL')], null=True),
        ),
    ]
