# Generated by Django 2.1.2 on 2020-08-10 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0076_merge_20200722_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('root_model', models.CharField(max_length=100)),
                ('distinct', models.BooleanField(default=False)),
                ('report_file', models.FileField(blank=True, upload_to='report_files')),
                ('report_file_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Builder',
                'verbose_name_plural': 'Reports Builder',
                'db_table': 'reports',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('ref_path', models.CharField(blank=True, max_length=300, null=True)),
                ('field', models.CharField(max_length=100)),
                ('is_custom_field', models.BooleanField(default=False)),
                ('custom_value', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=200)),
                ('is_sortable', models.BooleanField(default=False)),
                ('is_ascending', models.BooleanField(default=True)),
                ('width', models.IntegerField(default=15)),
                ('aggregate', models.CharField(blank=True, choices=[('Sum', 'Sum'), ('Count', 'Count'), ('Avg', 'Avg'), ('Max', 'Max'), ('Min', 'Min')], max_length=5)),
                ('is_total', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.Report')),
            ],
            options={
                'verbose_name': 'Report Builder - Field',
                'verbose_name_plural': 'Report Builder - Fields',
                'db_table': 'reports_fields',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ReportFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_path', models.CharField(blank=True, max_length=300, null=True)),
                ('field', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('is_exclude', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, max_length=10, null=True)),
                ('value1', models.CharField(blank=True, max_length=300, null=True)),
                ('value2', models.CharField(blank=True, max_length=300, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.Report')),
            ],
            options={
                'verbose_name': 'Report Builder - Filter',
                'verbose_name_plural': 'Report Builder - Filters',
                'db_table': 'reports_filters',
                'ordering': ('field',),
            },
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='report_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Contract'), (2, 'Chargeback'), (3, 'Manual'), (4, 'AMP'), (5, 'CB DETAIL')], null=True),
        ),
    ]
