# Generated by Django 2.1.2 on 2020-08-11 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0077_auto_20200811_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargebackdisputehistory',
            name='chargeback_ref',
            field=models.ForeignKey(blank=True, db_column='chargeback_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.ChargeBackHistory'),
        ),
        migrations.AlterField(
            model_name='chargebackdisputehistory',
            name='chargebackline_ref',
            field=models.ForeignKey(blank=True, db_column='chargebackline_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.ChargeBackLineHistory'),
        ),
    ]
