# Generated by Django 2.1.2 on 2020-08-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0077_auto_20200810_1114'),
        ('erms', '0077_auto_20200811_1333'),
    ]

    operations = [
    ]
