# Generated by Django 2.1.2 on 2020-08-13 08:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0078_auto_20200811_2245'),
        ('erms', '0078_merge_20200811_1341'),
    ]

    operations = [
    ]
