# Generated by Django 2.1.2 on 2020-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0079_merge_20200813_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebackline',
            name='disputes_codes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='chargebackline',
            name='disputes_notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='disputes_codes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='chargebacklinehistory',
            name='disputes_notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
