# Generated by Django 2.1.2 on 2020-08-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0080_auto_20200815_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfilter',
            name='date_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportfilter',
            name='is_run_parameter',
            field=models.BooleanField(default=False),
        ),
    ]
