# Generated by Django 3.1.2 on 2020-10-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0088_data852__data867'),
    ]

    operations = [
        migrations.AddField(
            model_name='data852',
            name='L_QE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
