# Generated by Django 3.1.2 on 2020-11-03 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0090_auto_20201019_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfield',
            name='case_default_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportfield',
            name='case_is_custom_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='field_type',
            field=models.SmallIntegerField(choices=[(1, 'System'), (2, 'Static'), (3, 'Calculated'), (4, 'Percent'), (5, 'Case Statement')], default=1),
        ),
        migrations.CreateModel(
            name='ReportCaseStatementField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('case_field_name', models.CharField(blank=True, max_length=300, null=True)),
                ('action', models.CharField(blank=True, max_length=10, null=True)),
                ('case_when_value', models.CharField(blank=True, max_length=100, null=True)),
                ('case_then_value', models.CharField(blank=True, max_length=100, null=True)),
                ('report_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erms.reportfield')),
            ],
            options={
                'verbose_name': 'Report Builder - Case Statement Field',
                'verbose_name_plural': 'Report Builder - Case Statement Fields',
                'db_table': 'reports_case_statement_fields',
            },
        ),
    ]
