# Generated by Django 3.1.2 on 2020-11-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0091_auto_20201103_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncenter',
            name='dea_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
