# Generated by Django 3.1.2 on 2020-11-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0092_auto_20201123_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='data852',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data852',
            name='wholesaler_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data867',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data867',
            name='wholesaler_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data852',
            name='H_distributor_id',
            field=models.ForeignKey(blank=True, db_column='H_distributor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.distributioncenter', to_field='dea_number'),
        ),
    ]
