# Generated by Django 3.1.2 on 2020-12-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0093_auto_20201123_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargebackline',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('A', 'Autocorrect'), ('O', 'Override'), ('D', 'Disputed'), ('N', 'None')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='chargebacklinehistory',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('A', 'Autocorrect'), ('O', 'Override'), ('D', 'Disputed'), ('N', 'None')], max_length=1, null=True),
        ),
    ]
