# Generated by Django 3.1.2 on 2021-01-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0096_auto_20210113_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='frequency',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Quartarly')], null=True),
        ),
    ]
