# Generated by Django 3.1.2 on 2021-01-22 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0097_auto_20210114_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_email', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, max_length=10, null=True)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('change_text', models.CharField(blank=True, max_length=300, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.contract')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.item')),
            ],
            options={
                'verbose_name': 'Contract Audit Trail',
                'verbose_name_plural': 'Contract Audit Trails',
                'db_table': 'contract_audit_trails',
            },
        ),
        migrations.AddIndex(
            model_name='contractaudittrail',
            index=models.Index(fields=['user_email'], name='con_audit_user_email'),
        ),
        migrations.AddIndex(
            model_name='contractaudittrail',
            index=models.Index(fields=['date'], name='con_audit_date'),
        ),
    ]
