# Generated by Django 3.1.1 on 2021-01-25 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0098_auto_20210122_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChargeBack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_mail', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('cblnid', models.IntegerField(blank=True, null=True)),
                ('change_text', models.TextField(blank=True, null=True)),
                ('cbid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erms.chargeback')),
            ],
            options={
                'verbose_name': 'Chargeback Audit Trail',
                'verbose_name_plural': 'Chargeback Audit Trails',
                'db_table': 'audit_chargeback',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='auditchargeback',
            index=models.Index(fields=['date'], name='cb_audit_date'),
        ),
        migrations.AddIndex(
            model_name='auditchargeback',
            index=models.Index(fields=['cblnid'], name='cb_audit_cblnid'),
        ),
        migrations.AddIndex(
            model_name='auditchargeback',
            index=models.Index(fields=['user_mail'], name='cb_audit_user_email'),
        ),
    ]
