# Generated by Django 3.1.2 on 2021-01-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0100_auto_20210125_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contractaudittrail',
            table='audit_contract',
        ),
    ]
