# Generated by Django 3.1.2 on 2021-06-21 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erms', '0103_reportdynamicstaticfield_static_dateformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('report_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=140, null=True)),
                ('date_run', models.DateField(blank=True, null=True)),
                ('time_run', models.DateTimeField(auto_now_add=True, null=True)),
                ('tables_used', models.TextField(blank=True, null=True)),
                ('result_lines', models.IntegerField(blank=True, null=True)),
                ('time_to_create', models.IntegerField(blank=True, null=True)),
                ('time_to_export', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Run Log',
                'verbose_name_plural': 'Report Run Log',
                'db_table': 'report_run_log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='reportrunlog',
            index=models.Index(fields=['email'], name='report_run__email_83eda0_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrunlog',
            index=models.Index(fields=['company_name'], name='report_run__company_f4eca4_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrunlog',
            index=models.Index(fields=['date_run'], name='report_run__date_ru_d1b35e_idx'),
        ),
    ]
