# Generated by Django 2.1.2 on 2019-04-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indirectcustomer',
            old_name='location_number',
            new_name='account_number',
        ),
    ]
