# Generated by Django 2.1.2 on 2019-04-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0004_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcustomer',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributioncenter',
            name='account_stid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='distributioncenter',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
