# Generated by Django 2.1.2 on 2019-04-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0008_directcustomer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='full_name',
        ),
        migrations.AddField(
            model_name='recipient',
            name='first_name',
            field=models.CharField(default='Jane', max_length=120),
        ),
        migrations.AddField(
            model_name='recipient',
            name='last_name',
            field=models.CharField(default='Doe', max_length=120),
        ),
    ]
