# Generated by Django 2.1.2 on 2019-04-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0009_auto_20190430_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
