# Generated by Django 2.1.2 on 2019-05-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0011_directcustomer_is_big3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directcustomer',
            name='is_big3',
        ),
        migrations.RemoveField(
            model_name='directcustomer',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='distributioncenter',
            name='old_id',
        ),
    ]
