# Generated by Django 2.1.2 on 2019-05-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0012_auto_20190502_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedreason',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='type',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('A', 'A'), ('I', 'I')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='distributioncenter',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ermm.DirectCustomer'),
        ),
    ]
