# Generated by Django 2.1.2 on 2019-05-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0013_auto_20190502_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='dispute_old_id',
        ),
    ]
