# Generated by Django 2.1.2 on 2019-06-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0014_remove_dispute_dispute_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directcustomer',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Distributor'), (2, 'GPO'), (3, 'Buying and Group'), (4, 'Parent')], null=True),
        ),
    ]
