# Generated by Django 2.1.2 on 2019-08-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0016_auto_20190802_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_quickbook_file',
            field=models.FileField(blank=True, upload_to='qb'),
        ),
    ]
