# Generated by Django 2.1.2 on 2019-08-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0017_company_last_quickbook_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='auto_contract_notification_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='automatic_chargeback_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='class_of_trade_validation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='membership_validation_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='proactive_membership_validation',
            field=models.BooleanField(default=False),
        ),
    ]
