# Generated by Django 2.1.2 on 2019-08-15 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ermm', '0018_auto_20190815_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOfTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.SmallIntegerField(choices=[(1, 'GOVERNMENT'), (2, 'DISTRIBUTION'), (3, 'PROVIDERS'), (4, 'RESIDENTIAL'), (5, 'NON-RETAIL PHARMACY'), (6, 'RETAIL PHARMACY'), (7, 'OTHER PURCHASERS'), (8, 'PAYERS')])),
                ('value', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classoftrade_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classoftrade_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class of Trade',
                'verbose_name_plural': 'Classes of Trades',
                'db_table': 'class_of_trade',
                'ordering': ('group', 'value'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='classoftrade',
            unique_together={('group', 'value')},
        ),
    ]
