# Generated by Django 2.1.2 on 2019-08-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0019_auto_20190815_2241'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='companysetting',
        #     unique_together=set(),
        # ),
        migrations.RemoveField(
            model_name='companysetting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companysetting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companysetting',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='company_setting',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CompanySetting',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
