# Generated by Django 2.1.2 on 2019-08-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0020_auto_20190816_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoftrade',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='indirectcustomer',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='indirectcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
