# Generated by Django 2.1.2 on 2019-08-29 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ermm', '0021_auto_20190819_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrationsystem_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrationsystem_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration System',
                'verbose_name_plural': 'Integration Systems',
                'db_table': 'integration_systems',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='integration_type',
        ),
        migrations.AddField(
            model_name='company',
            name='integration_config',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='integration_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ermm.IntegrationSystem'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationsystem',
            unique_together={('name',)},
        ),
    ]
