# Generated by Django 2.1.2 on 2019-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0022_auto_20190829_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='generate_transaction_number',
            field=models.BooleanField(default=False),
        ),
    ]
