# Generated by Django 2.1.2 on 2019-11-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0023_company_generate_transaction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_only_disputed_lines_in_849',
            field=models.BooleanField(default=True),
        ),
    ]
