# Generated by Django 2.1.2 on 2019-11-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0026_auto_20191129_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('order',), 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ('module', 'order'), 'verbose_name': 'View', 'verbose_name_plural': 'Views'},
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='view',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
