# Generated by Django 2.1.2 on 2019-12-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0028_auto_20191218_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edimappingtemplate',
            old_name='type',
            new_name='mapping_type',
        ),
        migrations.RenameField(
            model_name='edimappingtemplate',
            old_name='format',
            new_name='output_format',
        ),
        migrations.RenameField(
            model_name='edimappingtemplatedetail',
            old_name='edi_mapping_template',
            new_name='emt',
        ),
        migrations.RenameField(
            model_name='edimappingtemplatedetail',
            old_name='fixed_width_char',
            new_name='fw_char',
        ),
        migrations.RenameField(
            model_name='edimappingtemplatedetail',
            old_name='fixed_width_length',
            new_name='fw_length',
        ),
        migrations.RenameField(
            model_name='edimappingtemplatedetail',
            old_name='fixed_width_row',
            new_name='fw_row',
        ),
        migrations.RenameField(
            model_name='edimappingtemplatedetail',
            old_name='enable',
            new_name='is_enabled',
        ),
        migrations.RenameField(
            model_name='edimappingtemplatedetail',
            old_name='name',
            new_name='map_name',
        ),
        migrations.RenameField(
            model_name='edimappingtemplatedetail',
            old_name='segment',
            new_name='map_segment',
        ),
        migrations.AlterUniqueTogether(
            name='edimappingtemplatedetail',
            unique_together={('emt', 'map_name', 'map_segment')},
        ),
    ]
