# Generated by Django 2.1.2 on 2019-12-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermm', '0029_auto_20191218_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edimappingtemplate',
            name='document_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='edimappingtemplate',
            name='output_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
